name: Java API CI/CD on PR w/ tag
on:
  push:
    branches: [ "BCC-19/Inventory-entry-point" ]
  pull_request:
    branches: [ "main" ]
  
  # push:
  #   tags:
  #     - 'v*'  

jobs:
  build_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    - name: Inject application.yml
      run: |
        cd ./beancards
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        echo "spring:" > ./application.yml
        echo "  datasource:" >> ./application.yml
        echo "    url: ${{ secrets.DB_BUILD_URL }}" >> ./application.yml
        echo "    username: ${{ secrets.DOCKER_USERNAME }}" >> ./application.yml
        echo "    password: ${{ secrets.DOCKER_PASSWORD }}" >> ./application.yml
        echo "    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver" >> ./application.yml

    - name: Test & package
      run: |
        cd beancards
        mvn package -DskipTests
    
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build & Publish Docker image
      run: |
        cd beancards
        docker build -t ${{secrets.DOCKER_USERNAME}}/trader-g .
        docker push ${{secrets.DOCKER_USERNAME}}/trader-g:latest

  deploy_api:
    needs: build_api
    runs-on: self-hosted
    steps:
      - name: Pull image from docker
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/trader-g:latest
      - name: Delete old container
        run: sudo docker rm -f traderDBEC2
      - name: Run container
        run: sudo docker run -d -p 8080:8080 --name traderDBEC2 ${{secrets.DOCKER_USERNAME}}/trader-g:latest