name: "Database CI/CD"
 
on:
  push:
    branches: [ "BCC-19/Inventory-entry-point" ]
  pull_request:
    types:
      - closed
    branches:
      - main
      
 
jobs:
  Migrate:
    if: github.event.pull_request.merged == true
    name: RunMigration
    runs-on: ubuntu-20.04         
    steps:
      - name: RunMigration
        uses: actions/checkout@v3.0.0
      - run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.7.1/flyway /usr/local/bin
      - run: flyway -user="${{ secrets.DOCKER_USERNAME }}" -password="${{ secrets.DOCKER_PASSWORD }}" -url="${{ secrets.DB_BUILD_URL }}" info
      - run: flyway -user="${{ secrets.DOCKER_USERNAME }}" -password="${{ secrets.DOCKER_PASSWORD }}" -url="${{ secrets.DB_BUILD_URL }}" migrate
